const actionsConstants = {
    SUCCESS_REGISTRATION: 'SUCCESS_REGISTRATION',
    BAD_REGISTRATION: 'BAD_REGISTRATION',
    SUCCESS_AUTHORIZATION: 'SUCCESS_AUTHORIZATION',
    BAD_AUTHORIZATION: 'BAD_AUTHORIZATION',
    SUCCESS_UPDATE: 'SUCCESS_UPDATE',
    BAD_UPDATE: 'BAD_UPDATE',
    SUCCESS_CREATION: 'SUCCESS_CREATION',
    BAD_CREATION: 'BAD_CREATION'
}

export default actionsConstants;
